# fly.toml app configuration file generated for gancio-eventos-lhc on 2024-01-31T21:45:26-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gancio-eventos-lhc'
primary_region = 'gru'

[build]

[[mounts]]
  source = 'gancio_data'
  destination = '/data'

[http_service]
  internal_port = 13120
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
