name: 📅 Generate Backup Tarball File

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  schedule:
    name: 📅 Generate Backup Tarball File
    runs-on: ubuntu-latest
    steps:
      - uses: sozo-design/curl@v1.0.2
        with:
          args: https://eventos.lhc.net.br
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl ssh console -C "./backup.sh"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}